export default {
	SET_ACTIVE_DASHBOARD: 'SET_ACTIVE_DASHBOARD',
	SET_LAYOUTS: 'SET_LAYOUTS',
	CREATE_DASHBOARD: 'CREATE_DASHBOARD',
	UPDATE_DASHBOARD_NAME_PENDING: 'UPDATE_DASHBOARD_NAME_PENDING',
	UPDATE_DASHBOARD_NAME_SUCCESS: 'UPDATE_DASHBOARD_NAME_SUCCESS',
	UPDATE_DASHBOARD_NAME_FAILED: 'UPDATE_DASHBOARD_NAME_FAILED',
	CREATE_LAYOUT: 'CREATE_LAYOUT',
	DELETE_DASHBOARD: 'DELETE_DASHBOARD',
	SET_DASHBOARDS: 'SET_DASHBOARDS'
};
